UNAME_S := $(shell uname -s)

ifeq ($(UNAME_S),Linux)
GNU_INSTALL_ROOT = $(SFXTOOLS_BASE)/gcc-arm-none-eabi-5_4-2016q3
GNU_VERSION = 5.4.1
GNU_PREFIX = arm-none-eabi

NRFJPROG := $(SFXTOOLS_BASE)/nRF5x-Command-Line-Tools_9_6_0_Linux-x86_64/nrfjprog/nrfjprog
MERGEHEX := $(SFXTOOLS_BASE)/nRF5x-Command-Line-Tools_9_6_0_Linux-x86_64/mergehex/mergehex
NRFUTIL  := nrfutil
endif

ifeq ($(UNAME_S),Darwin)
GNU_INSTALL_ROOT = $(SFXTOOLS_BASE)/gcc-arm-none-eabi-5_4-2016q3-mac/
GNU_VERSION = 5.4.1
GNU_PREFIX = arm-none-eabi

NRFJPROG := $(SFXTOOLS_BASE)/nRF5x-Command-Line-Tools_9_5_0_OSX/nrfjprog/nrfjprog
MERGEHEX := $(SFXTOOLS_BASE)/nRF5x-Command-Line-Tools_9_5_0_OSX/mergehex/mergehex
NRFUTIL  := nrfutil
endif

